In [9]:
import numpy as np
import librosa
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
from typing import List, Tuple, Dict
from microphone import record_audio

%matplotlib notebook

In [24]:
class FingerprintKey:
    def __init__(self, key, ti):
        self.key = key # (fi, fj, delta_t)
        self.ti = ti

def load_audio(song_name):
    '''
    Return the recorded audio and sampling_rate as a Tuple
    '''
    return librosa.load(song_name)

def get_spectrogram(recorded_audio, sampling_rate):
    '''
    Return the spectrogram corresponding to `recorded_audio` with `sampling_rate` as the sampling_rate
    '''
    return mlab.specgram(recorded_audio,
                            NFFT=4096,
                            Fs=sampling_rate,
                            window=mlab.window_hanning,
                            noverlap=4096//2,
                            mode='magnitude')


def put_database(fingerprint_database: Dict[str, str], song_database: List[Tuple[str, str, str]], fingerprint, song):
    fingerprint_database[fingerprint] = song
    song_database.append(song)

In [25]:
recorded_audio, sampling_rate = load_audio('songs/Rasputin.mp3')
get_spectrogram(recorded_audio, sampling_rate)

/Users/ssharma/opt/anaconda3/lib/python3.8/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


(array([[0.00000000e+00, 0.00000000e+00, 2.04819625e-12, ...,
         2.23299283e-05, 1.91901538e-05, 1.16650308e-05],
        [0.00000000e+00, 0.00000000e+00, 2.04818595e-12, ...,
         1.21937431e-05, 1.13162338e-05, 8.89274677e-06],
        [0.00000000e+00, 0.00000000e+00, 2.04815506e-12, ...,
         1.18398302e-06, 4.36650477e-06, 4.78612868e-06],
        ...,
        [0.00000000e+00, 0.00000000e+00, 1.25211013e-13, ...,
         2.39122794e-09, 1.22186508e-09, 2.36473664e-10],
        [0.00000000e+00, 0.00000000e+00, 1.24643755e-13, ...,
         2.50600144e-09, 1.16038117e-09, 8.72642420e-11],
        [0.00000000e+00, 0.00000000e+00, 1.24454325e-13, ...,
         1.83981492e-09, 3.97419020e-10, 8.70001810e-12]]),
 array([0.00000000e+00, 5.38330078e+00, 1.07666016e+01, ...,
        1.10142334e+04, 1.10196167e+04, 1.10250000e+04]),
 array([9.28798186e-02, 1.85759637e-01, 2.78639456e-01, ...,
        2.65914921e+02, 2.66007800e+02, 2.66100680e+02]))